name: gift_shop
description: 'Gift Shop Flutter project.'
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.0.0
  provider: ^6.1.2
  # flutter_map: ^7.0.2
  # latlong2: ^0.9.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/products/
    - assets/images/artisans/
    - lib/assets/images/
